### ISSUE TITLE
Configuration against Slicer fails due to missing gsl headers

### ISSUE THREAD

**Issue by jcfr** [gaoyi/SlicerSPoM#3]
Attempting to configure the project by building against Slicer fails with the following error:

```bash
$ cmake \
    -DSlicer_DIR:PATH=/path/to/Slicer-Release/Slicer-build \
    -DCMAKE_BUILD_TYPE:STRING=Release \
  ../SlicerSPoM

[...]

CMake Error at PoissonShapeAnalysis/CMakeLists.txt:21 (find_path):
  Could not find GSL_INSTALLATION_PATH using the following files:
  include/gsl/gsl_math.h
```

The project should takes of building required dependencies not already provided by Slicer.

Alternatively the implementation should be updated to make use filters already available in ITK and/or VTK.

**Comment by jcfr** [comment]
Searching for `gsl` in the code base does not return any source file, this means the requirement for `gsl` was likely introduce by copying code from another projects ... or it became irrelevant after prior refactoring.

**Comment by gaoyi** [comment]
Yes the gsl was introduced by mistake. Your version with gsl removed has been merged.
