### ISSUE TITLE
Remove commented code and improve variable name in PoissonShapeAnalysis.cxx

### ISSUE THREAD

**Issue by jcfr** [gaoyi/SlicerSPoM#7]
* [PoissonShapeAnalysis/PoissonShapeAnalysis.cxx](https://github.com/gaoyi/SlicerSPoM/blob/main/PoissonShapeAnalysis/PoissonShapeAnalysis.cxx)

  * [ ] Remove commented code

  * [ ] Update internal variable `foo` to be more descriptive

**Comment by gaoyi** [comment]
These are done in 277e5921d0946dc1f83175f4a4132017e326d2de
